config/routes.rb
Cvweb::Application.routes.draw do
  resources :site_configs do
    put :change_leader, on: :collection, action: :change_leader
  end

  resources :jobs

  resources :races

  resources :requirements

  resources :news

  resources :shouts

  resources :rewards

  resources :events do
    resources :occurrences
    put :update_visible, on: :collection
  end

  resources :members do
    put :update_active, on: :collection
    put :update_admins, on: :collection
    get :attendances, on: :member
    put :begin_new_cycle, on: :member
  end

  get "home/index"

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "home#index"

end

app/models/shout.rb
class Shout < ActiveRecord::Base
  default_scope order("id desc")
  belongs_to :member
  attr_accessible :date, :text
  validates_presence_of :text, :member
  before_create :set_date

  private
  def set_date
    self.date = Time.now
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_filter(only: [:destroy, :edit, :update]) { |a| a.send(:authorize,:admin) }
  respond_to :html, :json

  def index
    @shouts = Shout.includes(:member).page(params[:page])
    respond_with @shouts
  end

  def show
    @shout = Shout.find(params[:id])
    respond_with @shout
  end

  def new
    @shout = Shout.new
    respond_with @shout
  end

  def edit
    @shout = Shout.find(params[:id])
  end

  def create
    @shout = Shout.new(params[:shout])
    @shout.member = current_member
    flash[:notice] = 'Shout was successfully created.' if @shout.save
    respond_with @shout
  end

  def update
    @shout = Shout.find(params[:id])
    flash[:notice] = 'Shout was successfully updated.' if @shout.update_attributes(params[:shout])
    respond_with @shout
  end

  def destroy
    @shout = Shout.find(params[:id])
    @shout.destroy
    respond_with @shout
  end
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/shouts/_form.html.haml
= form_for @shout do |f|
  - if @shout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shout.errors.count, "error")} prohibited this shout from being saved:"
      %ul
        - @shout.errors.full_messages.each do |msg|
          %li= msg

  .form-horizontal
    .control-group.field
      .control-label= f.label :text
      .controls= f.text_area :text, rows: 5
    .form-actions
      = f.submit 'Save', class: "btn btn-primary"
      - if @shout.persisted?
        = link_to 'Cancel', @shout, class: "btn btn-danger"
      - else
        = link_to 'Cancel', shouts_path, class: "btn btn-danger"

app/views/shouts/edit.html.haml
- content_for :title do
  Shouts - Editing

%h1 Editing shout

= render 'form'

app/views/shouts/index.html.haml
- content_for :title do
  Shouts

%h1.valigned Shouts
.pull-right
  = link_to new_shout_path, class: "btn btn-success" do
    %i.icon-plus-sign.icon-white
    = 'New Shout'

%table.table.table-condensed
  %tr
    %th Text
    %th Date
    %th #{@config.members.singularize}
    - if admin?
      %th

  - @shouts.each do |shout|
    %tr
      %td= shout.text
      %td= shout.date.to_date
      %td= link_to shout.member.name, shout.member
      - if admin?
        %td= link_to 'Destroy', shout, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

= paginate @shouts

app/views/shouts/new.html.haml
- content_for :title do
  Shouts - New shout

%h1 New shout

= render 'form'

app/views/shouts/show.html.haml
- content_for :title do
  Shouts - Shout

%p
  %b Text:
  = @shout.text
%p
  %b Date:
  = @shout.date
%p
  %b #{@config.members.singularize}:
  = @shout.member.name

- if @shout.member == current_member
  = link_to 'Edit', [:edit, @shout], class: "btn btn-info"
= link_to 'Back', shouts_path, class: "btn btn-primary"