config/routes.rb
Cvweb::Application.routes.draw do
  resources :site_configs do
    put :change_leader, on: :collection, action: :change_leader
  end

  resources :jobs

  resources :races

  resources :requirements

  resources :news

  resources :shouts

  resources :rewards

  resources :events do
    resources :occurrences
    put :update_visible, on: :collection
  end

  resources :members do
    put :update_active, on: :collection
    put :update_admins, on: :collection
    get :attendances, on: :member
    put :begin_new_cycle, on: :member
  end

  get "home/index"

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :visible, where{(hidden == false) | (hidden == nil)}
  default_scope order(:name)
  attr_accessible :hidden, :name, :points, :failure_points, :remarks, :time
  validates_presence_of :name, :points
  has_many :event_rewards, dependent: :destroy
  has_many :rewards, :through => :event_rewards
  has_many :occurrences, dependent: :destroy
  has_many :event_requirements, dependent: :destroy
  has_many :requirement_obtainments, dependent: :destroy
  validates_uniqueness_of :name
  validates :name, uri_eligibility: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  default_scope order(:name)
  attr_accessible :external_value, :name, :remarks, :event_rewards_attributes
  validates_presence_of :name
  has_many :event_rewards, :inverse_of => :reward, dependent: :destroy
  has_many :events, :through => :event_rewards
  has_many :character_rewards, dependent: :destroy
  validates_uniqueness_of :name
  validates :name, uri_eligibility: true
  accepts_nested_attributes_for :event_rewards, :allow_destroy => true

  def eligible(occurrence)
    character_rewards.includes(:character).includes(:occurrence).unobtained_or_occurrence(occurrence)
  end

  def freelot
    (Member.active - character_rewards.obtained.collect(&:member)).collect(&:characters).flatten
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter(except: [:index, :show]) { |a| a.send(:authorize,:leader) }

  respond_to :html, :json

  def index
    if params[:update_visible]
      @events = Event.all
      @update_visible = true
    else
      @events = Event.visible.page(params[:page])
    end
    respond_with @events
  end

  def show
    @event = Event.find_by_name(CGI.unescape params[:id])
    respond_with @event
  end

  def new
    @event = Event.new
    respond_with @event
  end

  def edit
    @event = Event.find_by_name(CGI.unescape params[:id])
  end

  def create
    @event = Event.new(params[:event])
    flash[:notice] = "#{@config.events.singularize.capitalize} was successfully created." if @event.save
    respond_with @event
  end

  def update
    @event = Event.find_by_name(CGI.unescape params[:id])
    flash[:notice] = "#{@config.events.singularize.capitalize} was successfully updated." if @event.update_attributes(params[:event])
    respond_with @event
  end

  def destroy
    @event = Event.find_by_name(CGI.unescape params[:id])
    @event.destroy
    respond_with @event
  end

  def update_visible
    if params[:event_ids].empty?
      Event.update_all(hidden: true)
    else
      Event.where(id: params[:event_ids]).update_all(hidden: false)
      Event.where{id.not_in my{params[:event_ids]}}.update_all(hidden: true)
    end
    redirect_to events_path
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .form-horizontal
    .control-group.field
      .control-label= f.label :name
      .controls= f.text_field :name
    .control-group.field
      .control-label= f.label :points
      .controls= f.number_field :points
    .control-group.field
      .control-label= f.label :failure_points
      .controls= f.number_field :failure_points
    .control-group.field
      .control-label= f.label :remarks
      .controls= f.text_field :remarks
    .control-group.field
      .control-label= f.label :hidden
      .controls= f.check_box :hidden
    .control-group.field
      .control-label= f.label :time
      .controls= f.time_select :time
    .form-actions
      = f.submit 'Save', class: "btn btn-primary"
      - if @event.persisted?
        = link_to 'Cancel', @event, class: "btn btn-danger"
      - else
        = link_to 'Cancel', events_path, class: "btn btn-danger"

app/views/events/edit.html.haml
- content_for :title do
  = @config.events.pluralize + " - Editing " + @event.name

%h1 Editing #{@config.events.singularize}

= render 'form'

app/views/events/index.html.haml
- content_for :title do
  = @config.events.pluralize

- if @update_visible
  = form_tag update_visible_events_path, method: :put
%h1.valigned= @config.events.pluralize
.pull-right
  - if leader?
    - if @update_visible
      = submit_tag 'Update Visible', class: "btn btn-primary"
      = link_to 'Cancel', events_path, class: "btn btn-danger"
    - else
      = link_to 'Update Visible', events_path(update_visible: 1), class: "btn btn-info"
      = link_to new_event_path, class: "btn btn-success" do
        %i.icon-plus-sign.icon-white
        = "New #{@config.events.singularize}"

%table.table.table-condensed
  %tr
    - if @update_visible
      %th
    %th Name
    %th Success
    %th Failure
    - if leader?
      %th
      %th

  - @events.each do |event|
    %tr
      - if @update_visible
        %td= check_box_tag "event_ids[]", event.id, !event.hidden, id: "visible_ids_#{event.id}"
      %td= link_to event.name, event
      %td
        .badge.badge-success= event.points || 0
      %td
        .badge.badge-important= event.failure_points || 0
      - if leader?
        %td= link_to 'Edit', [:edit, event], class: "btn btn-info"
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

- unless @update_visible
  = paginate @events

app/views/events/new.html.haml
- content_for :title do
  = @config.events.pluralize + " - New " + @config.events.singularize

%h1 New #{@config.events.singularize}

= render 'form'

app/views/events/show.html.haml
- content_for :title do
  = @config.events.pluralize + " - " + @event.name

%h1.valigned= @event.name
.pull-right
  = link_to "#{@config.occurrences}", event_occurrences_path(@event), class: "btn btn-success"
  - if leader?
    = link_to 'Edit', [:edit, @event], class: "btn btn-info"
  = link_to 'Back', events_path, class: "btn btn-primary"

%p
  .badge.badge-success= @event.points
  \/
  .badge.badge-important= @event.failure_points || 0
%p
  %b Remarks:
  = @event.remarks
%p
  %b Hidden:
  = @event.hidden
%p
  %b Time:
  = @event.time

.row
  -@event.rewards.each do |r|
    .span4
      %p= link_to r.name, r
      = render 'rewards/list', :reward => r

  - requirements_for = @event.event_requirements.includes(:requirement).collect(&:requirement)
  - unless requirements_for.empty?
    .span4
      %b #{@config.requirements.pluralize} For
      %ol
      - requirements_for.each do |req|
        %li= link_to req.name, req

  - requirements_from = @event.requirement_obtainments.collect(&:requirement)
  - unless requirements_from.empty?
    .span4
      %b #{@config.requirements.pluralize} Obtained From
      %ol
      - requirements_from.each do |req|
        %li= link_to req.name, req