config/routes.rb
Cvweb::Application.routes.draw do
  resources :site_configs do
    put :change_leader, on: :collection, action: :change_leader
  end

  resources :jobs

  resources :races

  resources :requirements

  resources :news

  resources :shouts

  resources :rewards

  resources :events do
    resources :occurrences
    put :update_visible, on: :collection
  end

  resources :members do
    put :update_active, on: :collection
    put :update_admins, on: :collection
    get :attendances, on: :member
    put :begin_new_cycle, on: :member
  end

  get "home/index"

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "home#index"

end

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title #{@config.site_name} #{yield :title}
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 

  %body
    .navbar.navbar-static-top
      #menu.navbar-inner
        = link_to @config.site_name, home_index_path, class: :brand
        %ul.nav.nav-pills
          %li{class: active_page_controller('members')}
            = link_to members_path, id: :members do
              %i.icon-user
              = @config.members
          %li{class: active_page_controller('events')}
            = link_to events_path, id: :events do
              %i.icon-flag
              = @config.events
          %li{class: active_page_controller('rewards')}
            = link_to rewards_path, id: :rewards do
              %i.icon-gift
              = @config.rewards
          %li.dropdown{class: active_page_controller('occurrences')}
            %a.dropdown-toggle{ data: {toggle: :dropdown}, href: "#"}
              %i.icon-calendar
              = @config.occurrences
              %b.caret
            %ul.dropdown-menu
              - event_list.each do |event|
                %li= link_to event.name, event_occurrences_path(event)
          %li{class: active_page_controller('shouts')}
            = link_to shouts_path, id: :shouts do
              %i.icon-bullhorn
              = 'Shout!'

          - if leader? || admin?
            %li.dropdown
              %a.dropdown-toggle{ :data => {toggle: "dropdown"}, href: "#"}
                %i.icon-pencil
                Configuration
                %b.caret
              %ul.dropdown-menu
                - if leader?
                  %li=link_to 'Site Config', site_configs_path, id: :site_configs
                  %li=link_to @config.jobs, jobs_path, id: :jobs
                  %li=link_to @config.races, races_path, id: :races
                  %li=link_to @config.requirements, requirements_path, id: :requirements
                %li=link_to "News", news_index_path, id: :news

        %ul.nav.pull-right
          %li.dropdown
            %a.dropdown-toggle{ :data => {toggle: "dropdown"}, href: "#"}
              = current_member.name
              %b.caret
            %ul.dropdown-menu
              %li=link_to 'My Page', @current_member
              %li=link_to 'Logout', logout_url, id: :logout

    .container 
      #main
        - if flash[:notice]
          #notice.message.alert.alert-success= flash[:notice]
        - elsif flash[:warning]
          #warning.message.alert= flash[:warning]
 
        = yield
  
      %p

app/views/layouts/logged_out.html.haml
!!! 5

%html
  %head
    %title= @config ? @config.site_name : "Cvweb"
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 

  %body
    .container
      %h1.title= @config ? @config.site_name : "Cvweb"
  
      #main
        - if flash[:notice]
          #notice.message.alert.alert-success= flash[:notice]
        - elsif flash[:warning]
          #warning.message.alert.alert-danger= flash[:warning]
  
      = yield