config/routes.rb
Cvweb::Application.routes.draw do
  resources :site_configs do
    put :change_leader, on: :collection, action: :change_leader
  end

  resources :jobs

  resources :races

  resources :requirements

  resources :news

  resources :shouts

  resources :rewards

  resources :events do
    resources :occurrences
    put :update_visible, on: :collection
  end

  resources :members do
    put :update_active, on: :collection
    put :update_admins, on: :collection
    get :attendances, on: :member
    put :begin_new_cycle, on: :member
  end

  get "home/index"

  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "home#index"

end

app/models/member.rb
class Member < ActiveRecord::Base
  scope :active, where{(active == true) | (active == nil)}
  scope :inactive, where(active: false)
  scope :admins, where{(admin == true) | (leader == true)}
  default_scope order(:name)
  attr_accessible :active, :name, :password, :password_confirmation, :remarks, :url, :characters_attributes, :character_rewards_attributes
  has_secure_password
  validates_presence_of :name, :password, :on => :create
  has_many :characters, :inverse_of => :member, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :shouts, dependent: :destroy
  has_many :event_attendances, :through => :characters
  has_many :jobs, :through => :characters
  has_many :attendances, source: :occurrence, through: :event_attendances
  has_many :character_rewards, dependent: :destroy
  has_many :occurrences
  validates_uniqueness_of :name
  validates_uniqueness_of :leader, allow_nil: true
  accepts_nested_attributes_for :characters, :reject_if => lambda { |a| a[:name].blank? }
  validate :has_character?
  validates :name, uri_eligibility: true
  accepts_nested_attributes_for :character_rewards
  before_validation :destroy_unset_character_rewards
  before_create :set_dates

  def self.leader
    where(leader: true).first
  end

  def attendance_rate(since_date = join_date)
    100 * (attendances.since(since_date).mandatory.points.to_f / Occurrence.since(since_date).mandatory.points)
  end

  def attendance_percentage
     100 * (total_points.to_f / EventAttendance.points)
  end
  
  def available_rewards
     Reward.all - character_rewards.includes(:reward).obtained.collect(&:reward)
  end

  def wishlist_length
    character_rewards.obtained.by_cycle(reward_cycle).count + available_rewards.count
  end

  def cycle_list(cycle)
    character_rewards.includes(:reward).by_cycle(cycle).includes(:occurrence => :event).order(:preference)
  end

  def build_all_character_jobs
    characters.each do |character|
      character.build_all_character_jobs(Job.all)
    end
  end

  def begin_new_cycle
    self.reward_cycle += 1
    self.cycle_date = get_last_reward_date
    self.current_points = 0
    characters.each do |character|
      character.current_points = 0
      character.save!
    end
    save!
  end

  def current_occurrence?(occurrence)
    cycle_date <= occurrence.to_date
  end

  private
  def get_last_reward_date
    character_rewards.obtained.where{preference.not_eq nil}.joins(:occurrence).maximum("occurrences.end_time")
  end

  def has_character?
    errors.add :base, "Member must have at least one character" if characters.blank?
  end

  def destroy_unset_character_rewards
    character_rewards.each do |cr|
      cr.mark_for_destruction if cr.reward_id.blank?
    end
  end

  def set_dates
    self.join_date ||= Time.now
    self.cycle_date ||= Time.now
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter(:only => [:destroy, :update_admins]) { |a| a.send(:authorize,:leader) }
  before_filter(:only => [:new, :create, :update_active]) { |a| a.send(:authorize,:admin) }
  before_filter :validate_member, :only => [:edit, :update, :begin_new_cycle]
  respond_to :html, :json

  def index
    if params[:update_active]
      @members = Member.all
      @update_active = true
    else
      @members = Member.active
      @members = @members.page(params[:page]) unless params[:update_admins]
      @update_admins =  params[:update_admins]
    end
    respond_with @members
  end

  def show
    @member = Member.find_by_name(CGI.unescape params[:id])
    @jobs = Job.all
    respond_with @member
  end

  def new
    @member = Member.new
    @member.characters.build
    load_related
    @available_rewards = Reward.all
    respond_with @member
  end

  def edit
    @member = Member.find_by_name(CGI.unescape params[:id])
    load_related
    @available_rewards = @member.available_rewards
  end

  def create
    @member = Member.new(params[:member])

    if @member.save
      flash[:notice] = "#{@config.members.singularize.capitalize} was successfully created."
    else
      load_related
      @available_rewards = Reward.all
      @member.characters.build if @member.characters.length == 0
    end
    respond_with @member
  end

  def update
    @member = Member.find_by_name(CGI.unescape params[:id])

    if @member.update_attributes(params[:member])
      flash[:notice] = "#{@config.members.singularize.capitalize} was successfully updated."
    else
      load_related
      @available_rewards = @member.available_rewards
    end
    respond_with @member
  end

  def destroy
    @member = Member.find_by_name(CGI.unescape params[:id])
    @member.destroy
    respond_with @member
  end

  def update_active
    Member.update_all(["active = id in (?)",params[:member_ids]])
    redirect_to members_path
  end

  def update_admins
    Member.update_all(["admin = id in (?)", params[:member_ids]])
    redirect_to members_path
  end

  # PUT /members/Name/begin_new_cycle
  def begin_new_cycle
    @member = Member.find_by_name(CGI.unescape params[:id])
    @member.begin_new_cycle
    redirect_to @member, notice: 'New Reward Cycle started.'
  end

  # GET /members/1/attendances
  # GET /members/1/attendances.json
  def attendances
    @member = Member.find_by_name(CGI.unescape params[:id])
    @attendances = @member.event_attendances.order_by_date.page(params[:page])

    respond_to do |format|
      format.html # attendances.html.erb
      format.json { render json: @member.event_attendances }
    end
  end

  private

  def validate_member
    unless current_member.to_param == params[:id] || admin?
      flash[:warning] = 'You may only edit yourself!'
      redirect_to Member.find_by_name(CGI.unescape params[:id])
    end
  end

  def load_related
    @races = Race.all
    @rewards = Reward.all
    @member.build_all_character_jobs
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_attendance_list.html.haml
%b Attendance 
%table.table.table-condensed
  %tr
    %th Date
    %th #{@config.events.singularize}
    - if @member.characters.many?
      %th Character
    %th Points
  - attendances.includes(:occurrence).includes(:event).includes(:character).each do |a|
    %tr
      %td= link_to a.occurrence.end_time.to_date, [a.event, a.occurrence]
      %td= link_to a.event.name, a.event
      - if @member.characters.many?
        %td= a.character.name
      %td
        - if a.occurrence.success
          .badge.badge-success= a.event.points
        - else
          .badge.badge-danger= a.event.failure_points

app/views/members/_character.html.haml
.well
  %h3 Character
  .form-horizontal
    .control-group.field
      .control-label.control-label= f.label :name
      .controls= f.text_field :name
    .control-group.field
      .control-label= f.label :remarks
      .controls= f.text_field :remarks
    .inline.field
      .control-label= label_tag :race, @config.races.singularize, :class => "checkbox inline"
      .controls
        - @races.each do |r|
          = f.label :race_id, r.name, :class => "checkbox inline"
          = f.radio_button :race_id, r.id, :class => "checkbox inline"
    .control-group.field
      .control-label= f.label :jobs, @config.jobs.pluralize
      .controls
        = f.fields_for :character_jobs do |cj|
          = render 'character_jobs', :f => cj
    .inline.field
      .control-label= f.label :sex, :class => "checkbox inline"
      .controls
        = f.hidden_field :sex, :value => "none"
        = f.label :sex, :Male, :value => "Male", :class => "checkbox inline"
        = f.radio_button :sex, "Male", :class => "checkbox inline"
        = f.label :sex, :Female, :value => "Female", :class => "checkbox inline"
        = f.radio_button :sex, "Female", :class => "checkbox inline"

app/views/members/_character_jobs.html.haml
.form-inline.field
  = f.check_box :_destroy, {:checked => f.object.persisted?}, 0, 1
  = f.label :_destroy, f.object.job.name
  = f.hidden_field :job_id, :value => f.object.job.id
  = f.label :level
  = f.number_field :level

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg
  .form-horizontal
    .control-group.field
      .control-label= f.label :name
      .controls= f.text_field :name
    .control-group.field
      .control-label= f.label :password
      .controls= f.password_field :password
    .control-group.field
      .control-label= f.label :password_confirmation
      .controls= f.password_field :password_confirmation
    .control-group.field
      .control-label= f.label :url
      .controls= f.text_field :url
    .control-group.field
      .control-label= f.label :remarks
      .controls= f.text_field :remarks
    .control-group.field
      .control-label= f.label :active, :Inactive
      .controls= f.check_box :active, {checked: @member.active==false}, 0, 1
    .control-group.field
      = f.fields_for :characters do |c|
        = render 'character', :f => c
      = link_to_add_fields "Add Character", f, :characters
    #wishlist.control-group.field
      %table.table.table-condensed
        %tr
          %th
          %th #{@config.rewards.singularize}
          - if @member.characters.many?
            %th Character
        - (1...@member.reward_cycle).each do |i|
          %tr
            %td #{i}.
            %td Unavailable (Reward cycle #{@member.reward_cycle})
        - @member.wishlist_length.times do |i|
          %tr
            - idx = i+@member.reward_cycle
            - next_cr = @member.character_rewards.where(reward_cycle: @member.reward_cycle).find{ |cr| cr.preference == idx}
            - next_cr ||= @member.character_rewards.build(preference: idx)
            %td #{idx}.
            - if next_cr.obtained
              %td= next_cr.reward.name
              - if @member.characters.many?
                %td= next_cr.character.name
            - else
              = f.fields_for :character_rewards, next_cr, :child_index => idx do |cr|
                %td= cr.collection_select :reward_id, @available_rewards, :id, :name, include_blank: ''
                - if @member.characters.many?
                  %td= cr.collection_select :character_id, @member.characters, :id, :name
                - else
                  = cr.hidden_field :character_id, value: @member.characters.first.id
                = cr.hidden_field :preference, value: i+1

    .form-actions
      = f.submit 'Save', class: "btn btn-primary"
      - if @member.persisted?
        = link_to 'Cancel', @member, class: "btn btn-danger"
      - else
        = link_to 'Cancel', members_path, class: "btn btn-danger"

= javascript_include_tag "member"

app/views/members/attendances.html.haml
- content_for :title do
  = @config.members.pluralize + " - " + @member.name + " Attendance"

%h1.valigned #{@member.name} Attendance

.pull-right
  = link_to 'Back', @member, class: "btn btn-primary"

%p

= render 'attendance_list', attendances: @attendances

= paginate @attendances

app/views/members/edit.html.haml
- content_for :title do
  = @config.members.pluralize + " - Editing " + @member.name

%h1 Editing #{@config.members.singularize}

= render 'form'

= link_to 'Begin New Reward Cycle', {action: :begin_new_cycle, id: @member}, {data: { confirm: 'This action can not be undone. Are you sure you want to start a new reward cycle?' }, method: :put, class: "btn btn-danger"}

app/views/members/index.html.haml
- content_for :title do
  = @config.members.pluralize

- if @update_active
  = form_tag update_active_members_path, method: :put
- elsif @update_admins
  = form_tag update_admins_members_path, method: :put
%h1.valigned= @config.members.pluralize
.pull-right
  - if admin?
    - if @update_active
      = submit_tag 'Update Active', class: "btn btn-primary"
      = link_to 'Cancel', members_path, class: "btn btn-danger"
    - elsif @update_admins
      = submit_tag 'Update Admins', class: "btn btn-primary"
      = link_to 'Cancel', members_path, class: "btn btn-danger"
    - else
      = link_to 'Update Admins', members_path(update_admins: 1), class: "btn btn-info"
      = link_to 'Update Active', members_path(update_active: 1), class: "btn btn-info"
      = link_to new_member_path, class: "btn btn-success" do
        %i.icon-plus-sign.icon-white
        = "New #{@config.members.singularize}"

%table.table.table-condensed
  %tr
    - if @update_active || @update_admins
      %th
    %th Name
    %th Points
    %th Join date
    %th Admin
    %th Leader
    %th Cycle
    %th Cycle date
    - if admin?
      %th
    - if leader?
      %th

  - @members.each do |member|
    %tr{id: member.name}
      - if @update_active
        %td= check_box_tag "member_ids[]", member.id, member.active, id: "member_ids_#{member.id}"
      - if @update_admins
        %td= check_box_tag "member_ids[]", member.id, member.admin, id: "member_ids_#{member.id}"
      %td= link_to member.name, member
      %td
        .badge.badge-success= member.current_points
      %td= member.join_date
      %td
        -if member.admin
          %i.icon-ok
      %td
        -if member.leader
          %i.icon-ok
      %td= member.reward_cycle
      %td= member.cycle_date
      - if admin?
        %td= link_to 'Edit', [:edit, member], class: "btn btn-info"
      - if leader?
        %td= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"

- unless @update_active || @update_admins
  = paginate @members

app/views/members/new.html.haml
- content_for :title do
  = @config.members.pluralize + " - New " + @config.members.singularize

%h1 New #{@config.members.singularize}

= render 'form'

app/views/members/show.html.haml
- content_for :title do
  = @config.members.pluralize + " - " + @member.name

%h1.valigned= @member.name
.pull-right
  - if admin? || @member == current_member
    = link_to 'Edit', [:edit, @member], class: "btn btn-info"
  = link_to 'Back', members_path, class: "btn btn-primary"

%p
  .badge.badge-success= @member.current_points
  \/
  .badge.badge-info= @member.total_points

%p
  %b Join date:
  = @member.join_date
%p
  %b Url:
  = @member.url
%p
  %b Remarks:
  = @member.remarks
%p
  %b Active:
  = @member.active
%p
  %b Admin:
  = @member.admin
%p
  %b Leader:
  = @member.leader
%p
  %b Reward cycle:
  = @member.reward_cycle
%p
  %b Cycle date:
  = @member.cycle_date

%p#character_list
  %b Characters
  %table.table.table-condensed
    %tr
      %th Name
      %th Points
      %th Remarks
      %th Sex
      %th #{@config.races.singularize}
    - @member.characters.includes(:race).includes(:member).each do |c|
      %tr
        %td= c.name
        %td
          .badge.badge-success= c.current_points
        %td= c.remarks
        %td= c.sex
        %td= c.race.try :name

- member_jobs = @member.jobs
- unless member_jobs.empty?
  #character_jobs
    %table.table.table-condensed
      %tr
        %th= @config.jobs.pluralize
        - @member.characters.each do |c|
          %th= c.name
      - member_jobs.each do |j|
        %tr
          %td= j.name
          - @member.characters.includes(:character_jobs).each do |c|
            %td
              -if c.jobs.include?(j)
                %i.icon-ok

.row
  .span5 
    %p#attendance_list
      = render 'attendance_list', attendances: @member.event_attendances.order_by_date.limit(10)
      = link_to 'See all attendance', [:attendances, @member]

    %p
      %b Attendance rate:
      = @member.attendance_rate.round(2)

    %p
      %b Attendance percentage:
      = @member.attendance_percentage.round(2)

  - wishlist = @member.cycle_list(@member.reward_cycle).unobtained
  - unless wishlist.empty?
    .span5
      %b Wishlist
      %table.table.table-condensed#wishlist
        %tr
          %th #
          %th #{@config.rewards.singularize}
          %th Points
          - if @member.characters.many?
            %th Character
        - wishlist.each do |r|
          %tr
            %td #{r.preference}.
            %td= link_to r.reward.name, r.reward
            %td
              .badge.badge-info= r.current_points.round(2)
            - if @member.characters.many?
              %td= r.character.name

  #obtained_list
    - (1..@member.reward_cycle).each do |cycle|
      - cycle_list = @member.cycle_list(cycle).obtained
      - unless cycle_list.empty?
        .span5
          %b #{@config.rewards.pluralize} Obtained Cycle #{cycle}
          %table.table.table-condensed
            %tr
              %th #
              %th #{@config.rewards.singularize}
              %th Date
              %th Points
              - if @member.characters.many?
                %th Character
            - cycle_list.each do |r|
              - if r.obtained
                %tr
                  %td= r.preference
                  %td= link_to r.reward.name, r.reward
                  %td= link_to r.occurrence.end_time.to_date, [r.occurrence.event, r.occurrence] unless r.occurrence.nil?
                  %td
                    .badge.badge-info= r.obtained_points.round(2)
                  - if @member.characters.many?
                    %td= r.character.name

    - freelots = @member.character_rewards.includes(:reward).free_lot.includes(:occurrence => :event)
    - unless freelots.empty?
      .span4
        %b Free lots
        %table.table.table-condensed
          %tr
            %th #{@config.rewards.singularize}
            %th Date
            - if @member.characters.many?
              %th Character
          - freelots.each do |r|
            - if r.obtained
              %tr
                %td= link_to r.reward.name, r.reward
                %td= link_to r.occurrence.end_time.to_date, [r.occurrence.event, r.occurrence] unless r.occurrence.nil?
                - if @member.characters.many?
                  %td= r.character.name